"""Make file_record_id optional for email-only approach

Revision ID: make_file_record_optional
Revises: add_contact_number
Create Date: 2024-11-16 13:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'make_file_record_optional'
down_revision = 'add_contact_number'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Make file_record_id nullable for email-only approach
    op.alter_column('order_items', 'file_record_id',
                    existing_type=sa.String(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'file_record_id',
                    existing_type=sa.String(),
                    nullable=False)
    # ### end Alembic commands ###